### ISSUE TITLE
Clean AppDelegate 

### ISSUE THREAD

**Issue by markgravity** [nimblehq/NimbleExtension#23]
I think we can make our AppDelegate cleaner by creating a register for framework/service that needs to register in AppDelegate.

AppDelegate.swift
```swift
class AppDelegate: BaseAppDelegate {

    override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        bootstrap.register(
            application: application,
            launchOptions: launchOptions,
            plugins:
            FacebookRegister.self
        )
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
}
```

FacebookRegisters.swift
```swift
class FacebookRegister: NSObject, PluginRegisterable, UIApplicationDelegate {
    var isPersistent: Bool = true
    
    func configure(application: UIApplication, launchOptions: [UIApplication.LaunchOptionsKey : Any]?) {
        ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
        Settings.isAutoLogAppEventsEnabled = true
        Settings.isAdvertiserIDCollectionEnabled = true
    }
    
    func applicationDidBecomeActive(_ application: UIApplication) {
        AppEvents.activateApp()
    }
    
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        let handled = ApplicationDelegate.shared.application(app, open: url, options: options)
        return handled
    }
}
```

So, it's easier to register/remove a framework/service from AppDelegate

**Comment by edgarss** [comment]
What is bootstrap supposed to be in the code sample?

Why not just have an extension AppDelegate+Facebook.swift in a seperate file to clean up AppDelegate?

```
extension AppDelegate {
    func configure() {
        Settings.isAutoLogAppEventsEnabled = true
        Settings.isAdvertiserIDCollectionEnabled = true
    }
}
```

**Comment by markgravity** [comment]
> What is bootstrap supposed to be in the code sample?

It's the bridge between a register and AppDelegate. 
Ex: It will call `configure` function from a register when `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool` is called


> Why not just have an extension AppDelegate+Facebook.swift in a seperate file to clean up AppDelegate?

An extension can't solve the problem such as when there is more than one framework/service need to call inside `func applicationDidBecomeActive(_ application: UIApplication)` for example 😃
