### ISSUE TITLE
Main Thread Execution: Improving the usage of `DispatchQueue.main`

### ISSUE THREAD

**Issue by minhnimble** [nimblehq/NimbleExtension#27]
This improvement suggestion is a clone from DeeMoney iOS project: https://github.com/dee-money/passenger-ios/issues/210

## Why

Normally, when we want to execute a block of code on main thread, what we would usually do is putting that block of code inside `DispatchQueue.main.async`. This way works just fine, especially in the case the code is currently running on background thread. 

However, in the situation when the block of code is already running on main thread, this action will cause the block of code to be rescheduled to run on main thread in the next runloop instead of the current one, causing a small delay in execution. An example symptom we usually see can be if the code is about showing some subviews, there will be a slight delay then a sudden pop to show the view.

## Further comment, evidence, alternatives considered

As a result, for solving this problem, we can create a `Thread+Async.swift` extension file for adding a current thread check before executing as follow:
```
extension Thread {

    static func performOnMain(_ execution: @escaping EmptyCompletion) {
        guard !Thread.isMainThread else { return execution() }
        DispatchQueue.main.async { execution() }
    }
}
```

Then, whenever we want to bring some code to main thread, instead of putting it inside `DispatchQueue.main.async`, we can do this 🤗
```
Thread.performOnMain {
   ...
   // execute your code on main thread here
   ...
}
```

**Comment by blyscuit** [comment]
I want to put this as referrence https://developer.apple.com/forums/thread/99224. My little research didn't find any downside to this except check Thread.isMainThread might be cpu costly (I don't know how much).
Good suggestion. 👍

**Comment by minhnimble** [comment]
> except check Thread.isMainThread might be cpu costly (I don't know how much).

I have tried to look for mentions about CPU cost of this check `Thread.isMainThread` on the internet but there is none that I could find 😅. Taking a closer look on [Apple document](https://developer.apple.com/documentation/foundation/thread/1408455-ismainthread), this check seems to be a computed boolean based on a stored variable - thread type of a Thread object, so I assume the cost is small enough to reach to a point where it is not worth mentioning 😁
