### ISSUE TITLE
Avoid using any force !

### ISSUE THREAD

**Issue by dekablade01** [nimblehq/NimbleExtension#8]
I found there're some table view extension using `force_casting`. 

Let's return exactly the same as normal tableView's function. Also these repository is extension. It means that this code is kind of hidden code. Let's make it simple as possible. 

![picture](https://i.imgur.com/ukXMcZm.png)

also this will crash the app when cell is not registered or cannot be casted. Imagine someone dequeue the cell without testing and it is missed in code review. The app will crash on production or on tester hand.

**Comment by suho** [comment]
I don't understand your mean about `return exactly the same as normal tableView's function`. Could you explain more?

**Comment by dekablade01** [comment]
in `UITableView` class, there're function to dequeue cells and headers. They return CellType and HeaderType with optional type. Because there are cases that the cell cannot be dequeue some how . 

Let's keep it's behavior by returning optional type

```swift
  public func dequeue<T: UITableViewCell>(_ name: T.Type) -> T? {
        return dequeueReusableCell(withIdentifier: String(describing: name)) as? T
    }

    public func dequeue<T: UITableViewCell>(_ name: T.Type, for indexPath: IndexPath) -> T? {
        return dequeueReusableCell(withIdentifier: String(describing: name), for: indexPath) as? T
    }

    public func dequeue<T: UITableViewHeaderFooterView>(_ name: T.Type) -> T? {
        return dequeueReusableHeaderFooterView(withIdentifier: String(describing: name)) as? T
    }

    public func register<T: UITableViewHeaderFooterView>(_ name: T.Type) {
        register(T.self, forHeaderFooterViewReuseIdentifier: String(describing: name))
    }

    public func register<T: UITableViewCell>(_ name: T.Type) {
        register(T.self, forCellReuseIdentifier: String(describing: name))
    }
```

**Comment by jasonnam** [comment]
Ya! Could you also setup SwiftLint here?

**Comment by suho** [comment]
> Ya! Could you also setup SwiftLint here?

Yes, will add to the project
